modules/cabinet/controllers/SiteController.php
<?php

namespace app\modules\cabinet\controllers;

use app\components\Helper;
use app\models\Requests;
use app\models\SiteSetting;
use app\models\Users;
use PHPUnit\TextUI\Help;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

/**
 * Default controller for the `cabinet` module
 */
class SiteController extends Controller
{
    public function beforeAction($action)
    {
        $csrf_disabled = ['calls'];
        if (Yii::$app->user->isGuest && Yii::$app->controller->action->id != 'login') {
            return $this->redirect(['site/login'])->send();
        }
        if (in_array(Yii::$app->controller->action->id, $csrf_disabled))
        {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionLogin()
    {

        $this->layout = 'main-login';
        if (Yii::$app->request->isPost) {
//            var_dump($_POST);die;
            $user = Users::find()->where(['username' => $_POST['Users']['username']])->one();
            if ($user && $user->validatePassword($_POST['Users']['password'])) {
                Yii::$app->user->login($user);
                return $this->redirect(['site/index'])->send();
            } else {
                Yii::$app->session->setFlash('login-error', 'Логин или пароль неверный!');
            }
        }
        $model = new Users();
        return $this->render('login', compact('model'));
    }

    public function actionCalls($show = '')
    {
        $query = Requests::find()->orderBy(['id' => SORT_DESC]);
        if ($show === 'spam') $query->where(['status' => Helper::CALL_SPAM]);
        else {
            $spam_status = Helper::CALL_SPAM;
            $query->where("status != {$spam_status}");
        }
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 30,
            ]
        ]);
        if(Yii::$app->request->isAjax && Yii::$app->request->isPost)
        {
            $data = Yii::$app->request->post();
            $request_id = explode(':', $data['id'])[1];
            $request_value = $data['value'];
            $request = Requests::findOne($request_id);
            if ($request_value == Helper::CALL_SPAM)
            {
                $request->status = Helper::CALL_SPAM;
                if($request->save())
                    return $this->asJson(['success' => true, 'action' => 'row-delete']);
                 else return $this->asJson(['success' => false, 'message' => 'Что-то пошло не так!']);
            }
            if ($request && is_numeric($request_value))
            {
                $request->status = (int)$request_value;
                return $this->asJson(['success' => $request->save(), 'html' => Helper::CallStatus($request_value)]);
            }
        }
        return $this->render('calls', compact('dataProvider'));
    }
    public function actionEditContact(){
        if (Yii::$app->request->isPost)
        {
            $post = Yii::$app->request->post();
            $model = SiteSetting::findOne(1);
            $model->address = $post['address'];
            $model->phone = $post['phone'];
            $model->phone2 = $post['phone2'];
            $model->email = $post['email'];
            if($model->save())
            {
               Yii::$app->session->setFlash('setting_success', 'Контактные данные обновлены');
            } else Yii::$app->session->setFlash('setting_error', 'Не удалось обновить данные =(');

        }
        return $this->render('edit_contact');
    }
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect(['site/login']);
    }
    public function actionPremium(){
        return $this->render('premium');
    }
}

modules/cabinet/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>


<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

modules/cabinet/views/layouts/header.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">АДТ</span><span class="logo-lg">На сайт</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
                <li>
                    <a href="<?=Url::to(['site/logout'])?>">Выход</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

modules/cabinet/views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="/images/users/1.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?=Yii::$app->user->identity->name?></p>

                <a href="#"><i class="fa fa-circle text-success"></i> Онлайн</a>
            </div>
        </div>


        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget'=> 'tree'],
                'items' => [
                    ['label' => 'Доступные инструменты', 'options' => ['class' => 'header']],
                    ['label' => 'На главную', 'icon' => 'home', 'url' => ['site/index']],
                    ['label' => 'Заявки на звонок', 'icon' => 'phone-square', 'url' => ['site/calls']],
                    ['label' => 'Изменить контакты', 'icon' => 'book', 'url' => ['site/edit-contact']],


                    ['label' => 'Дополнительные инструменты', 'options' => ['class' => 'header']],

                    ['label' => 'Аналитика посетителей', 'icon' => 'line-chart', 'url' => ['site/premium']],
                    ['label' => 'Изменить резюме', 'icon' => 'info-circle', 'url' => ['site/premium']],
                    ['label' => 'Изменить фотографии', 'icon' => 'photo', 'url' => ['site/premium']],
                    ['label' => 'Изменить услуги и цены', 'icon' => 'cubes', 'url' => ['site/premium']],
                    ['label' => 'Редактор карты', 'icon' => 'map-o', 'url' => ['site/premium']],
                    ['label' => 'Настройки сайта', 'icon' => 'gear', 'url' => ['site/premium']],

                ],
            ]
        ) ?>

    </section>

</aside>

modules/cabinet/views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/cabinet/views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\modules\cabinet\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" href="/favicon.png" type="image/x-icon">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <style>
        /* STOCK-LIKES ADMIN COLORS */
        .skin-blue .wrapper,
        .skin-blue .main-sidebar,
        .skin-blue .left-side {
            background-color: #2a3042 !important;
        }

        .skin-blue .sidebar-menu > li.header {
            color: #a6b0cf !important;
            background: #1a222645 !important;
        }

        .skin-blue .main-header .logo {
            background-color: #2a3042 !important;
        }

        .skin-blue .main-header .navbar {
            background-color: #2a3042 !important;
        }

        .skin-blue .main-header .logo:hover {
            background-color: #2c334a !important;
        }

        span.color-red {
            color: crimson !important;
        }

        .skin-blue .sidebar-menu > li:hover > a,
        .skin-blue .sidebar-menu > li.active > a,
        .skin-blue .sidebar-menu > li.menu-open > a {
            background: #262c3a !important;
        }

        .skin-blue .sidebar-menu > li > .treeview-menu {
            background: rgb(36 42 55) !important;
        }

        .skin-blue .main-header .navbar .sidebar-toggle:hover {
            background-color: #262c3a !important;
        }

        .skin-blue .sidebar-menu > li.active > a {
            border-left-color: crimson !important;
        }

        /* STOCK-LIKES ADMIN COLORS */
    </style>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>

modules/cabinet/views/site/calls.php
<?php
use yii\grid\GridView;
$this->title = 'Заявки на обратный звонок';
$isSpam = (!empty($_GET['show']) && $_GET['show'] === 'spam');
?>
<div class="box">
    <div class="box-header">
        <?php if ($isSpam): ?>
            <a href="/кабинет/звонки" class="btn btn-warning pull-right">Скрыть спам</a>
        <?php else: ?>
            <a href="/кабинет/звонки?show=spam" class="btn btn-warning pull-right">Показать спам</a>
        <?php endif; ?>
    </div>
    <div class="box-body">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                [
                    'attribute' => 'id',
                    'label' => 'Номер заявки'
                ],
                [
                    'attribute' => 'name',
                    'label' => 'Имя',
                    'format' => 'text'

                ],
                [
                    'attribute' => 'number',
                    'label' => 'Номер телефона',
                    'format' => 'html',
                    'value' => function($data){
                        return '<a href="tel:'.$data->number.'">' . $data->number . '</a>';
                    }
                ],
                [
                    'attribute' => 'question',
                    'label' => 'Вопрос',
                    'format' => 'text'
                ],
                [
                    'attribute' => 'from',
                    'label' => 'С какой формы заявка',
                    'format' => 'html',
                    'value' => function($data){
                        return \app\components\Helper::FromRequest($data->from);
                    }
                ],
                [
                    'attribute' => 'status',
                    'label' => 'Статус заявки',
                    'format' => 'html',
                    'value' => function($data){
                        return \app\components\Helper::CallStatus($data->status);
                    }
                ],
                [
                    'attribute' => 'created_at',
                    'label' => 'Дата заявки',
                    'format' => 'html',
                    'value' => function($data){
                        if (!empty($data->created_at)) return date('d-m-Y в H:i:s', $data->created_at);
                        else return '<span style="color:rgba(255, 0, 0, 0.3); font-style: italic;">(Не задано)</span>';
                    }
                ],
                [
                    'label' => 'Управление заявкой',
                    'format' => 'raw',
                    'value' => function($data){
                        return \app\components\Helper::renderManagementBtn($data->id, $data->status);
                    }
                ],

                // ...
            ],
        ]) ?>
    </div>
</div>
<script>
    function message(message, type, delay = 5000)
    {
        // full settings http://bootstrap-notify.remabledesigns.com/
        $.notify({
            message,
        }, {

            type,
            placement:
                {
                    from: "bottom",
                    align: "right"
                },
            delay
        });
    }

    document.addEventListener('change', (e)=>{
        if(e.target.tagName === 'SELECT')
        {

            $.ajax({
                url:'/кабинет/звонки',
                type:'post',
                data:{
                    id: e.target.id,
                    value: e.target.value
                },
                success: (data) => {
                    if(data.success) {
                        if (data.action === 'row-delete')
                        {
                            let row_id = e.target.getAttribute('call-id')
                            document.querySelector('[data-key="' + row_id +'"]').remove();
                            message('Запись успешно помечена как спам!', 'success');
                        } else {
                            message('Статус успешно изменен!', 'success');
                            e.target.parentElement.parentElement.querySelectorAll('td')[5].innerHTML = data.html;
                        }

                    } else {
                        message(data.message, 'error');
                    }
                },
                dataType: 'json'

            });
        }
    });
</script>

modules/cabinet/views/site/edit_contact.php
<?php

use app\models\SiteSetting;

$this->title = 'Изменить контактные данные';
?>
<div class="row">
    <div class="col-md-4">
        <?php if(Yii::$app->session->hasFlash('setting_success')):?>
        <div class="alert alert-success">
            <?=Yii::$app->session->getFlash('setting_success')?>
        </div>
        <?php endif;?>
        <form class="form" method="post">
            <input type="hidden" name="<?=Yii::$app->request->csrfParam; ?>" value="<?=Yii::$app->request->getCsrfToken(); ?>" />
            <div class="form-group">
                <label for="address">Адрес</label>
                <input class="form-control" type="text" id="address" name="address" value="<?=SiteSetting::findOne(1)->address?>">
            </div>
            <div class="form-group">
                <label for="phone">Номер телефона</label>
                <input class="form-control" type="text" id="phone" name="phone" value="<?=SiteSetting::findOne(1)->phone?>">
            </div>
            <div class="form-group">
                <label for="phone2">Второй номер телефона</label>
                <input class="form-control" type="text" id="phone2" name="phone2" value="<?=SiteSetting::findOne(1)->phone2?>">
            </div>
            <div class="form-group">
                <label for="email">Электронная почта</label>
                <input class="form-control" type="email" id="email" name="email" value="<?=SiteSetting::findOne(1)->email?>">
            </div>
            <input type="submit" value="Сохранить" class="btn btn-success btn-block">
        </form>
    </div>
</div>

modules/cabinet/views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

modules/cabinet/views/site/index.php
<?php
$this->title = 'Личный кабинет';
?>
<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="fa fa-phone"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Всего заявок</span>
                <span class="info-box-number"><?=\app\models\Requests::find()->count();?></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-red"><i class="fa fa-close"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Не отвеченных</span>
                <span class="info-box-number"><?=\app\models\Requests::find()->where(['status' => \app\components\Helper::CALL_NO_ANSWER])->count();?></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>

    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="fa fa-circle"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Отвеченных</span>
                <span class="info-box-number"><?=\app\models\Requests::find()->where(['status' => \app\components\Helper::CALL_ANSWER])->count();?></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-check"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Успешных</span>
                <span class="info-box-number"><?=\app\models\Requests::find()->where(['status' => \app\components\Helper::CALL_SUCCESS])->count();?></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
</div>
<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <p><strong>Всего заявок — </strong> Общее количество всех заявок с сайта, на обратный звонок</p>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <p><strong>Не отвеченных — </strong>Количество заявок с сайта на обратный звонок, у которых статус <i>"Не отвечен"</i></p>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <p><strong>Отвеченных — </strong> Количество заявок с сайт на обратный звонок и у которых был совершен перезвон и имеет статус <i>"Отвечен"</i></p>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <p><strong>Всего заявок — </strong> Количество заявок с сайта на обратный звонок, которые принесли деньги</p>
    </div>
</div>

modules/cabinet/views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Личный кабинет';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><b>Кабинет</b> адвоката</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
        <?php if (Yii::$app->session->hasFlash('login-error')):?>
        <div class="alert alert-danger">
            <?=Yii::$app->session->getFlash('login-error')?>
        </div>
        <?php endif;?>
        <p class="login-box-msg">Войдите чтобы продолжить <?=(Yii::$app->user->isGuest)?'гость':'нет'?></p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form
            ->field($model, 'username', $fieldOptions1)
            ->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('Ваш логин')]) ?>

        <?= $form
            ->field($model, 'password', $fieldOptions2)
            ->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('Ваш пароль')]) ?>

        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
            <!-- /.col -->
        </div>


        <?php ActiveForm::end(); ?>



    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->

modules/cabinet/views/site/premium.php
<?php
$this->title = 'Дополнительный премиум функционал';
?>

<style>

    .premium{
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
        grid-auto-rows: auto;
        grid-gap: 45px;
        padding:40px;
    }
    .premium-block{
        background: #ffffff;
        border-radius: 14px;
        padding: 15px;
        box-shadow: 0 7px 9px -6px black;
        transition: .3s;
        display: flex;
        flex-direction: column;
    }
    .premium-block:hover{
        transform: scale(1.05);
        cursor: pointer;
    }
    .premium-title{
        font-size: 2.3rem;
        text-align: center;
    }
    .premium-text{
        font-size: 16px;
    }
    .premium-ico{
        text-align: center;
        font-size: 14rem;
    }
    .premium-btn{
        margin-top: auto;
    }
    .premium-btn > .btn {
        margin-top: 30px;
    }
    .btn-black:hover{
        background-color: #363a48;
        border-color: #363a48;
        color:white;
    }
    .btn-black{
        background-color: #2a3042;
        border-color: #2a3042;
        color: white;
    }
    @media (max-width: 767px) {
        .premium{
            grid-gap: 25px;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        }
    }
    .buy_block{
        font-size: 18px;
    }
</style>

<div class="premium">
    <div class="premium-block" onclick="buy('Аналитика посетителей', 'line-chart', '500')">
        <div class="premium-title">Аналитика посетителей</div>
        <div class="premium-ico"><i class="fa fa-line-chart" style="color: #1bbda7;"></i></div>
        <div class="premium-text">
            <p>С помощью аналитики Вы сможете узнать: откуда пришел пользователь, с какого устройства он вошел, сколько времени провел на сайте, какого возраста, с какого города, страны и многое другое.</p>
            <p>Данная функция позволяет детально анализировать всех пользователей сайта которые когда либо к вам заходили.</p>
        </div>
        <div class="premium-btn">
            <div class="btn btn-black btn-block">Купить</div>
        </div>
    </div>
    <div class="premium-block" onclick="buy('Изменить резюме', 'info-circle', '500')">
        <div class="premium-title">Изменить резюме</div>
        <div class="premium-ico"><i class="fa fa-info-circle" style="color: #1b89bd;"></i></div>
        <div class="premium-text">
            <p>Данная функция позволяет вам в любое время без каких либо знаний изменить информацию по вашему <strong>резюме</strong> на сайте.
            </p>
        </div>
        <div class="premium-btn">
            <div class="btn btn-black btn-block">Купить</div>
        </div>
    </div>
    <div class="premium-block" onclick="buy('Изменить фото', 'photo', '1000')">
        <div class="premium-title">Изменить фото</div>
        <div class="premium-ico"><i class="fa fa-photo" style="color: crimson;"></i></div>
        <div class="premium-text">
            <p>Изменить или добавить новые фотографии на сайт сайт так же просто как и изменять резюме</p>
            <p>Чем лучше фотография на сайте, тем больше шансов то что ваш потенциальный клиент позвонит именно Вам!</p>
        </div>
        <div class="premium-btn">
            <div class="btn btn-black btn-block">Купить</div>
        </div>
    </div>
    <div class="premium-block" onclick="buy('Изменить услуги и цены', 'cubes', '1000')">
        <div class="premium-title">Изменить услуги и цены</div>
        <div class="premium-ico"><i class="fa fa-cubes" style="color: #4d1d8c;"></i></div>
        <div class="premium-text">
            <p>Если у вас вдруг неожиданно изменились цены на ваши услуги, либо появились новые, вы с легкостью можете это сделать через меню "Изменить услуги"</p>
            <p>Имея под рукой такой инструмент ваш клиент будет всегда вкурсе актуальных цен.</p>
        </div>
        <div class="premium-btn">
            <div class="btn btn-black btn-block">Купить</div>
        </div>
    </div>
    <div class="premium-block" onclick="buy('Редактор карты', 'map-o', '500')">
        <div class="premium-title">Редактор карты</div>
        <div class="premium-ico"><i class="fa fa-map-o" style="color: #b5620c;"></i></div>
        <div class="premium-text">
            <p>В самом низу страницы находится Яндекс карта.</p>
            <p>Если у вас сменился адрес офиса, вам нужно сменить адрес на карте и чтобы изменить адрес на данной карте по требуется помощь программиста</p>
            <p>С помощью инструмента "Редактор карты", вы справитесь сами!</p>
        </div>
        <div class="premium-btn">
            <div class="btn btn-black btn-block">Купить</div>
        </div>
    </div>
    <div class="premium-block" onclick="buy('Настройки сайта', 'gear', '1500')">
        <div class="premium-title">Полные настройки сайта</div>
        <div class="premium-ico"><i class="fa fa-gear" style="color: #2a3042;"></i></div>
        <div class="premium-text">
            <p>В полной настройки сайте вы сможете вносить следующие изменения на сайте:</p>

            <ol>
                <li>Изменять пункты меню</li>
                <li>Изменять логотип</li>
                <li>Заголовок сайта</li>
                <li>Описание сайта</li>
                <li>Ключевые слова для поиска</li>
                <li>А так же цветовую тему </li>
            </ol>
        </div>
        <div class="premium-btn">
            <div class="btn btn-black btn-block">Купить</div>
        </div>
    </div>
</div>
<script>
    function buy(what = '', icon = '', price = '1000'){
        Swal.fire({
            title: `<span style="font-size: 20px">Хороший выбор!</span>`,
            html:
                `<div class="buy_block">
                    <i class="fa fa-${icon}" style="color: #1bbda7; font-size:175px"></i>
                    <p>Чтобы купить функцию <u>${what}</u>:</p>
                    <p><strong>!</strong> Позвонить мне лично <a href="tel:+79373553841">+7-937-355-38-41</a> (Влад) и я вам все расскажу.</p>
                    <hr>
                    <strong>Либо</strong>
                    <hr>

                    <p><strong>!</strong> Перевести ${price} рублей на Сбербанк по номеру телефона: <a href="tel:+79373553841">+7-937-355-38-41</a></p>
                    <p><strong>!</strong> Обязательно в комментариях к платежу указать какой ваш сайт и выбранную услугу.</p>
                </div>
`,
            width:500,
            showCloseButton: true,
            showCancelButton: false,
            focusConfirm: true,
            confirmButtonText:
                '<i class="fa fa-thumbs-up"></i> Все понятно, спасибо!',

        })
    }
</script>